INSERT INTO `language` (`ID`, `LAN_ID`, `LAN_TXT`) VALUES
(521, 2, 'Homepage'), 
(522, 2, 'Timeframe'), 
(523, 2, 'For arranging the rooms for this point in time, please double click the requested time.'), 
(524, 2, 'Edit lecture'), 
(525, 2, 'Edit module'), 
(526, 2, 'Show standard room of this class'), 
(527, 2, 'Show laboratories'), 
(528, 2, 'Show miscellaneous rooms'), 
(529, 2, 'Backward'), 
(530, 2, 'Forward'), 
(531, 2, 'This module needs more than one room. Please use the room scheduling.'), 
(532, 2, 'The standard room isn't available for this time. Please use the room scheduling.'), 
(533, 2, 'The standard room isn't available for this time. Please use the room scheduling.'), 
(534, 2, 'For this point of time a lecture is already planned.'), 
(535, 2, 'All needed lectures have already been planned.'), 


INSERT INTO `language` (`ID`, `LAN_ID`, `LAN_TXT`) VALUES 
(521, 1, 'Zur Startseite'), 
(522, 1, 'Zeitraum'), 
(523, 1, 'Zum Bearbeiten der Räume zu diesem Zeitpunkt klicken Sie bitte doppelt auf die gewünschte Zeit.'), 
(524, 1, 'Vorlesung bearbeiten'), 
(525, 1, 'Modul bearbeiten'), 
(526, 1, 'Standardräume dieser Seminargruppe anzeigen'), 
(527, 1, 'Labore anzeigen'), 
(528, 1, 'Sonstige Räume anzeigen'), 
(529, 1, 'Zurück'), 
(530, 1, 'Weiter'), 
(531, 1, 'Dieses Modul benötigt mehrere Räume. Bitte legen Sie diese in der Raumplanung fest.'), 
(532, 1, 'Der Standardraum für dieses Modul ist zu diesem Termin leider bereits von einer anderen Seminargruppe belegt.'), 
(533, 1, 'Der Standardraum für diese Vorlesung ist zu diesem Termin leider bereits von einer anderen Seminargruppe belegt.'), 
(534, 1, 'Zu diesem Zeitpunkt ist bereits eine andere Vorlesung geplant.'), 
(535, 1, 'Sämtliche Vorlesungen dieses Faches, die laut Curriculum vorgeschrieben sind, sind bereits verplant.'), 
(536, 1, 'Zu diesem Zeitpunkt ist bereits eine andere Vorlesung geplant.'); 
