//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisched.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unisched.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        internal static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozent.
        /// </summary>
        internal static string Dozent {
            get {
                return ResourceManager.GetString("Dozent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fach.
        /// </summary>
        internal static string Fach {
            get {
                return ResourceManager.GetString("Fach", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan erstellen.
        /// </summary>
        internal static string Plan_erstellen {
            get {
                return ResourceManager.GetString("Plan_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planerstellung.
        /// </summary>
        internal static string Planerstellung {
            get {
                return ResourceManager.GetString("Planerstellung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raum.
        /// </summary>
        internal static string Raum {
            get {
                return ResourceManager.GetString("Raum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Änderungen werden erst nach einem Neustart der Anwendung übernommen. Wollen Sie die Anwendung neustarten?.
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustart zum Übernehmen von Änderungen.
        /// </summary>
        internal static string RestartMessageTitle {
            get {
                return ResourceManager.GetString("RestartMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminargruppe.
        /// </summary>
        internal static string Seminargruppe {
            get {
                return ResourceManager.GetString("Seminargruppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammdatenpflege.
        /// </summary>
        internal static string Stammdatenpflege {
            get {
                return ResourceManager.GetString("Stammdatenpflege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardraum.
        /// </summary>
        internal static string Standardraum {
            get {
                return ResourceManager.GetString("Standardraum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studienrichtung.
        /// </summary>
        internal static string Studienrichtung {
            get {
                return ResourceManager.GetString("Studienrichtung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studienzeitraum.
        /// </summary>
        internal static string Studienzeitraum {
            get {
                return ResourceManager.GetString("Studienzeitraum", resourceCulture);
            }
        }
    }
}
